basePath: /v1
definitions:
  entities.ChangePasswordInputSchema:
    properties:
      new_password:
        type: string
      new_password_confirm:
        type: string
      old_password:
        type: string
    type: object
  entities.CreateSpotInputSchema:
    properties:
      location:
        type: string
      title:
        type: string
    type: object
  entities.LoginInputSchema:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  entities.SignUpInputSchema:
    properties:
      email:
        type: string
      password:
        type: string
      password_confirm:
        type: string
      username:
        type: string
    type: object
  entities.Spot:
    properties:
      author:
        type: string
      created_at:
        type: string
      id:
        type: integer
      location:
        type: string
      title:
        type: string
      updated_at:
        type: string
      user:
        $ref: '#/definitions/entities.User'
      user_id:
        type: integer
    type: object
  entities.UpdateSpotSchema:
    properties:
      location:
        type: string
      title:
        type: string
    type: object
  entities.User:
    properties:
      email:
        type: string
      id:
        type: integer
      password:
        type: string
      username:
        type: string
    type: object
  presenter.JsonResponse:
    properties:
      data: {}
      error:
        type: boolean
      message:
        type: string
    type: object
info:
  contact:
    email: ggorockee@gmail.com
    name: ggorockee
  description: This is an API for ggocamping Application
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: ggocamping App
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login
      parameters:
      - description: Login Schema
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/entities.LoginInputSchema'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/presenter.JsonResponse'
            - properties:
                data:
                  type: string
              type: object
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/presenter.JsonResponse'
      summary: Login
      tags:
      - Auth
  /healthcheck:
    get:
      consumes:
      - application/json
      description: Health Check
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/presenter.JsonResponse'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/presenter.JsonResponse'
      summary: Health Check
      tags:
      - HealthCheck
  /spot:
    get:
      consumes:
      - application/json
      description: GetAllSpots
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/presenter.JsonResponse'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/presenter.JsonResponse'
      summary: GetAllSpots
      tags:
      - Spot
    post:
      consumes:
      - application/json
      description: AddSpot
      parameters:
      - description: Create Spot
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/entities.CreateSpotInputSchema'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/presenter.JsonResponse'
            - properties:
                data:
                  $ref: '#/definitions/entities.Spot'
              type: object
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/presenter.JsonResponse'
      security:
      - Bearer: []
      summary: AddSpot
      tags:
      - Spot
  /spot/{id}:
    delete:
      consumes:
      - application/json
      description: RemoveSpot
      parameters:
      - description: Spot id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/presenter.JsonResponse'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/presenter.JsonResponse'
      security:
      - Bearer: []
      summary: RemoveSpot
      tags:
      - Spot
    get:
      consumes:
      - application/json
      description: GetSpot
      parameters:
      - description: Spot id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/presenter.JsonResponse'
            - properties:
                data:
                  $ref: '#/definitions/entities.Spot'
              type: object
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/presenter.JsonResponse'
      security:
      - Bearer: []
      summary: GetSpot
      tags:
      - Spot
    put:
      consumes:
      - application/json
      description: UpdateSpot
      parameters:
      - description: Spot id
        in: path
        name: id
        required: true
        type: integer
      - description: Update Spot
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/entities.UpdateSpotSchema'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/presenter.JsonResponse'
            - properties:
                data:
                  $ref: '#/definitions/entities.Spot'
              type: object
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/presenter.JsonResponse'
      security:
      - Bearer: []
      summary: UpdateSpot
      tags:
      - Spot
  /spot/me:
    get:
      consumes:
      - application/json
      description: GetMySpots
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/presenter.JsonResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/entities.Spot'
                  type: array
              type: object
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/presenter.JsonResponse'
      security:
      - Bearer: []
      summary: GetMySpots
      tags:
      - Spot
  /user/changepw:
    put:
      consumes:
      - application/json
      description: ChangePassword
      parameters:
      - description: Change Password
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/entities.ChangePasswordInputSchema'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/presenter.JsonResponse'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/presenter.JsonResponse'
      security:
      - Bearer: []
      summary: ChangePassword
      tags:
      - Users
  /user/signup:
    post:
      consumes:
      - application/json
      description: Create User
      parameters:
      - description: Register user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/entities.SignUpInputSchema'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/presenter.JsonResponse'
            - properties:
                data:
                  $ref: '#/definitions/entities.User'
              type: object
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/presenter.JsonResponse'
      summary: Create User
      tags:
      - Users
securityDefinitions:
  Bearer:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
