version: "3.8"
services:
  db:
    build:
      context: ./mysql

    env_file:
      - ".env"

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

    volumes:
      - "./mysql/db_data:/var/lib/mysql"

    ports:
      - "${DB_PORT}:3306"