name: Docker Image CI

on:
  push:
    branches: [ "main" ]

env:
  GIT_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
  TARGET_REPOSITORY: ${{ vars.DEVOPS_REPOSITORY }}
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  REPOSITORY_NAME: camping-backend-with-go
  DOCKERFILE: Dockerfile

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      SHA: ${{ env.SHA }}
    steps:
    - name: Set short git commit SHA
      uses: benjlevesque/short-sha@v3.0
      id: short-sha
      with:
        length: 8
    - run: echo $SHA
      env:
        SHA: ${{ steps.short-sha.outputs.sha }}
    - name: set variables
      uses: marcdomain/set-variables@v1.2
      with:
        variables: |
          SHA: "${{ env.SHA }}"
    
    - name: Checkout 
      uses: actions/checkout@v4
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ env.DOCKERHUB_TOKEN }}
    
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ env.DOCKERHUB_USERNAME }}/${{ env.REPOSITORY_NAME }}:v-${{ env.SHA }}
        file: ${{ env.DOCKERFILE }}
      

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
    - name: checkout ${{ env.TARGET_REPOSITORY }} repository
      uses: actions/checkout@v4
      with:
        repository: ${{ env.TARGET_REPOSITORY }}
        token: ${{ env.GIT_TOKEN }}
        ref: 'main'

    - name: check directory
      run: |
        ls helm-values/dev/ggocamping-backend

    - uses: mikefarah/yq@master
      with:
        cmd: yq eval 'deployment.image.tag' = "v-${{ needs.build-and-push.outputs.SHA }}" helm-values/dev/ggocamping-backend/values.yaml --inplace

    - name: Commit changes
      run: |
        git config --local user.email "ggorockee@gmail.com"
        git config --local user.name "ggorockee"
        git add .
        git commit -m "CI: Update airbnb-server image tag to v-${{ needs.build-and-push.outputs.SHA }}"

    - name: Push Changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ env.GIT_TOKEN }}
        branch: main

#    - uses: fjogeleit/yaml-update-action@main
#      with:
#        valueFile: 'helm-values/dev/ggocamping-backend/values.yaml'
#        propertyPath: 'deployment.image.tag'
#        value: "v-${{ needs.build-and-push.outputs.SHA }}"
#        message: 'CI: Update airbnb-server image tag to v-${{ needs.build-and-push.outputs.SHA }}'
#        commitChange: true
#        branch: main
#        repository: ${{ env.TARGET_REPOSITORY }}
#        token: ${{ env.GIT_TOKEN }}